FROM node:18-alpine
WORKDIR /usr/local/apps/restapi

COPY .npmrc ./

COPY package.json ./
RUN yarn install --force
ENV PATH=/usr/local/restapi/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/restapi/dev
COPY tsconfig.json ./

COPY src ./src
COPY .env ./

CMD ["npm", "run", "start:watch"]
